### ISSUE TITLE
UIMA Log4jLogger_impl not compatible with log4j 2.18.0+

### ISSUE THREAD

**Issue by reckart** [apache/uima-uimaj#267]
**Describe the bug**
The class `org.apache.logging.slf4j.Log4jMarker` is no longer public in log4j versions >= 2.18.0

**To Reproduce**
1. Upgrade log4j dependency to 2.18.0 or higher
2. Run `de.tudarmstadt.ukp.clarin.webanno.api.type.CASMetadataTest`

**Expected behavior**
Should work.

**Please complete the following information:**
 - Version: 3.3.1

**Comment by reckart** [comment]
Added a nasty workaround using reflection. An alternative solution would be better....

**Comment by DrZ7** [comment]
when will 3.3.2 be released?
